export enum ServerPackets {
  SPAWN_ENTITY = 'SPAWN_ENTITY',
  SPAWN_ENTITY_CHARACTER = 'SPAWN_ENTITY_CHARACTER',
  SPAWN_ENTITY_HUMANOID = 'SPAWN_ENTITY_HUMANOID',
  SPAWN_PLAYER = 'SPAWN_PLAYER',
  PLAYER_LEFT = 'PLAYER_LEFT',
  INIT_LEVEL = 'INIT_LEVEL',
  PLAYER_INPUT_MOVE = 'PLAYER_INPUT_MOVE',
  SYNC_SNAPSHOT = 'SYNC_SNAPSHOT',
  PONG = 'PONG',
}
