export enum ClientPackets {
  CLIENT_INIT = 'CLIENT_INIT',
  MOVE_INPUT = 'MOVE_INPUT',
  ATTACK_INPUT = 'ATTACK_INPUT',
  PING = 'PING',
  PING2 = 'PING2',
  CLIENT_SYNC = 'CLIENT_SYNC',
  EQUIP_ARMOR = 'EQUIP_ARMOR',
  EQUIP_WEAPON = 'EQUIP_WEAPON',
  ENTITY_ATTACK = 'ENTITY_ATTACK',
  RESPAWN = 'RESPAWN',
}
